Repository vesoft-inc/nebula-common, pull requests merged in 2020-12, with the labels that each got.

#330 Fix the wrong usage for LRUCache
  src/common/base/ConcurrentLRUCache.h
  src/common/base/test/ConcurrentLRUCacheTest.cpp
Labels: ready-for-review, ready-for-testing

#329 Fix logical expression
  src/common/datatypes/Value.cpp
  src/common/datatypes/test/ValueTest.cpp
  src/common/expression/LogicalExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#332 fixed single quote error for fulltext index
  src/common/plugin/fulltext/FTUtils.h
  src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
  src/common/plugin/fulltext/elasticsearch/ESStorageAdapter.cpp
Labels: documentation, ready-for-review, ready-for-testing

#333 fix ErrorCode typo
  src/common/graph/Response.h
  src/common/interface/graph.thrift
Labels: ready-for-review, ready-for-testing

#331 update go thrift package path
  cmake/ThriftGenerate.cmake
Labels: ready-for-review, ready-for-testing

#334 if storage rpc return leader_change, but not set leader host, may core
  src/common/clients/storage/StorageClientBase.h
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-testing

#325 Show host graph
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#312 Upgrade cpplint.py
  .linters/cpp/cpplint.py
Labels: ready-for-review, ready-for-testing

#338 Revert "Upgrade cpplint.py"
  .linters/cpp/cpplint.py
Labels: ready-for-testing

#335 fix BitOp
  src/common/datatypes/Value.cpp
  src/common/datatypes/test/ValueTest.cpp
  src/common/function/AggregateFunction.h
  src/common/function/test/AggregateFunctionTest.cpp
Labels: ready-for-review, ready-for-testing

#250 toss common
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/clients/storage/CMakeLists.txt
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/clients/storage/GraphStorageClient.h
  src/common/clients/storage/InternalStorageClient.cpp
  src/common/clients/storage/InternalStorageClient.h
  src/common/clients/storage/StorageClientBase.h
  src/common/interface/CMakeLists.txt
  src/common/interface/meta.thrift
  src/common/interface/storage.thrift
Labels: ready-for-testing

#341 Rename typename of containers in thrift
  src/common/datatypes/ListOps.h
  src/common/datatypes/MapOps.h
  src/common/datatypes/SetOps.h
  src/common/datatypes/ValueOps.h
  src/common/interface/common.thrift
Labels: ready-for-testing

#288 Added an API for backup.
  src/common/clients/meta/MetaClient.cpp
  src/common/interface/common.thrift
  src/common/interface/meta.thrift
  src/common/interface/storage.thrift
Labels: ready-for-review, ready-for-testing

#343 Revert "Added an API for backup."
  src/common/clients/meta/MetaClient.cpp
  src/common/interface/common.thrift
  src/common/interface/meta.thrift
  src/common/interface/storage.thrift
Labels: ready-for-testing

#324 Support balance in job manager
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#339 add noloop function
  src/common/datatypes/Path.cpp
  src/common/datatypes/Path.h
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-testing

#336 fix abs and pow
  src/common/function/FunctionManager.cpp
Labels: ready-for-review, ready-for-testing

#310 get data from meta leader
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
Labels: ready-for-review, ready-for-testing

#323 unify all storage interface behavior
  src/common/base/Base.h
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/interface/storage.thrift
Labels: hold on, ready-for-review, ready-for-testing

#340 getResponse throw not appropriate exception if leader changed
  src/common/clients/storage/StorageClientBase.h
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-review, ready-for-testing

#344 Added an API for backup/restore.
  src/common/clients/meta/MetaClient.cpp
  src/common/interface/common.thrift
  src/common/interface/meta.thrift
  src/common/interface/storage.thrift
Labels: ready-for-review, ready-for-testing

#352 internal storage client needs to retry using a different port
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/clients/storage/InternalStorageClient.cpp
  src/common/clients/storage/InternalStorageClient.h
  src/common/clients/storage/StorageClientBase.h
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-review, ready-for-testing

#358 Add reverse path func.
  src/common/datatypes/Path.h
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
  src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.h
  src/common/plugin/fulltext/test/FulltextPluginTest.cpp
Labels: ready-for-testing

#223 Support sessions saving by metad
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/graph/Response.h
  src/common/interface/common.thrift
  src/common/interface/graph.thrift
  src/common/interface/meta.thrift
  src/common/thrift/ThriftTypes.h
Labels: ready-for-testing

#350 Rename the ops file to avoid install.
  src/common/datatypes/DataSetOps.inl
  src/common/datatypes/DateOps.inl
  src/common/datatypes/EdgeOps.inl
  src/common/datatypes/HostAddrOps.inl
  src/common/datatypes/KeyValueOps.inl
  src/common/datatypes/ListOps.inl
  src/common/datatypes/MapOps.inl
  src/common/datatypes/PathOps.inl
  src/common/datatypes/SetOps.inl
  src/common/datatypes/ValueOps.inl
  src/common/datatypes/VertexOps.inl
  src/common/expression/Expression.cpp
  src/common/graph/AuthResponseOps.inl
  src/common/graph/ExecutionResponseOps.inl
  src/common/graph/PairOps.inl
  src/common/graph/PlanDescriptionOps.inl
  src/common/graph/PlanNodeBranchInfoOps.inl
  src/common/graph/PlanNodeDescriptionOps.inl
  src/common/graph/ProfilingStatsOps.inl
  src/common/interface/common.thrift
  src/common/interface/graph.thrift
Labels: ready-for-testing

#357 Remove the bind of meta client from the interface of manager.
  src/common/meta/IndexManager.cpp
  src/common/meta/IndexManager.h
  src/common/meta/SchemaManager.cpp
  src/common/meta/SchemaManager.h
  src/common/meta/ServerBasedIndexManager.cpp
  src/common/meta/ServerBasedIndexManager.h
  src/common/meta/ServerBasedSchemaManager.cpp
  src/common/meta/ServerBasedSchemaManager.h
Labels: ready-for-testing

#356 Fix install third-party
  cmake/nebula/InstallThirdParty.cmake
Labels: ready-for-testing

#361 Fix drop index
  src/common/clients/meta/MetaClient.cpp
Labels: ready-for-testing

#342 support balance data reset plan
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#359 remove ENABLE_NATIVE
  CMakeLists.txt
Labels: ready-for-review, ready-for-testing

#351 support integer id
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/clients/storage/GraphStorageClient.h
  src/common/datatypes/Edge.cpp
  src/common/datatypes/Edge.h
  src/common/datatypes/EdgeOps.inl
  src/common/datatypes/Path.cpp
  src/common/datatypes/Vertex.cpp
  src/common/datatypes/Vertex.h
  src/common/datatypes/VertexOps.inl
  src/common/datatypes/test/EdgeTest.cpp
  src/common/datatypes/test/PathTest.cpp
  src/common/datatypes/test/ValueTest.cpp
  src/common/expression/PathBuildExpression.cpp
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
  src/common/interface/common.thrift
  src/common/interface/storage.thrift
  src/common/thrift/ThriftTypes.h
Labels: documentation, ready-for-testing

#360 Support proxygen lib
  cmake/nebula/ThirdPartyConfig.cmake
Labels: ready-for-testing

#365 ignore suggest-override warning in gcc
  cmake/nebula/GeneralCompilerConfig.cmake
Labels: ready-for-review, ready-for-testing

#367 fixed metad dump when port already in use
  src/common/webservice/WebService.cpp
Labels: bug, ready-for-review, ready-for-testing

#363 Support operator+ of List
  src/common/datatypes/Value.cpp
  src/common/datatypes/test/ValueTest.cpp
Labels: ready-for-testing

#369 Modify string timestamp format to function expression
  src/common/function/CMakeLists.txt
  src/common/function/FunctionManager.cpp
  src/common/function/TimeFunction.cpp
  src/common/function/TimeFunction.h
  src/common/function/test/CMakeLists.txt
  src/common/function/test/FunctionManagerTest.cpp
  src/common/function/test/TimeFunctionTest.cpp
  src/common/time/TimeUtils.cpp
  src/common/time/TimeUtils.h
  src/common/time/test/TimeUtilsTest.cpp
Labels: documentation, ready-for-testing

#319 Add list comprehension expression
  src/common/expression/CMakeLists.txt
  src/common/expression/CaseExpression.h
  src/common/expression/ExprVisitor.h
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/ListComprehensionExpression.cpp
  src/common/expression/ListComprehensionExpression.h
  src/common/expression/test/EncodeDecodeTest.cpp
  src/common/expression/test/ExpressionContextMock.h
  src/common/expression/test/ExpressionTest.cpp
Labels: documentation, ready-for-review, ready-for-testing

#370 Fix lookup bug
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-testing

#347 Change listening device of WebService to any
  src/common/http/test/HttpClientTest.cpp
  src/common/webservice/WebService.cpp
Labels: ready-for-testing

#362 fixed unstable testcase of plugin_fulltext_test
  src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.h
  src/common/plugin/fulltext/test/FulltextPluginTest.cpp
Labels: ready-for-review, ready-for-testing

#371 Fix parallel thrift codegen
  CMakeLists.txt
  cmake/ThriftGenerate.cmake
Labels: ready-for-testing

#372 Remove the GIT_INFO_SHA definition from compile option
  cmake/nebula/GitInfoConfig.cmake
Labels: ready-for-testing

#364 *Simple* Remove dependency on Readline and NCursor
  cmake/nebula/ThirdPartyConfig.cmake
Labels: ready-for-testing

#366 Support part distribute
  src/common/clients/storage/StorageClientBase.inl
  src/common/interface/meta.thrift
  src/common/meta/SchemaManager.h
  src/common/meta/ServerBasedSchemaManager.cpp
  src/common/meta/ServerBasedSchemaManager.h
Labels: ready-for-review, ready-for-testing

#373 Move versionString to graph and storage repos
  cmake/nebula/GitInfoConfig.cmake
  src/common/base/Base.cpp
  src/common/base/Base.h
Labels: ready-for-testing
