Repository vesoft-inc/nebula-common, pull requests merged in 2020-10, with the labels that each got.

#251 add <comparator for time and datetime
  src/common/datatypes/Date.h
  src/common/datatypes/Value.cpp
  src/common/datatypes/test/ValueTest.cpp
Labels: ready-for-testing

#253 added StartsWith() and EndsWith() in RelationalExpression.cpp
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/RelationalExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-testing

#245 Support zone
  src/common/base/Status.cpp
  src/common/base/Status.h
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
  src/common/thrift/ThriftTypes.h
Labels: documentation, ready-for-testing

#263 add getSpaceVidType
  src/common/meta/SchemaManager.h
  src/common/meta/ServerBasedSchemaManager.cpp
  src/common/meta/ServerBasedSchemaManager.h
Labels: ready-for-review, ready-for-testing

#262 Update thrift generator for Golang
  cmake/ThriftGenerate.cmake
Labels: ready-for-review, ready-for-testing

#211 Support to save default value to expression
  src/common/clients/meta/MetaClient.cpp
  src/common/interface/meta.thrift
  src/common/meta/NebulaSchemaProvider.cpp
  src/common/meta/NebulaSchemaProvider.h
  src/common/meta/SchemaProviderIf.h
Labels: ready-for-testing

#266 support get all vertice on tag, get all edges on edgetype
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/storage.thrift
  src/common/meta/IndexManager.h
  src/common/meta/ServerBasedIndexManager.cpp
  src/common/meta/ServerBasedIndexManager.h
Labels: ready-for-review, ready-for-testing

#268 Avoid items copy in container expression
  src/common/expression/ContainerExpression.h
  src/common/expression/FunctionCallExpression.h
  src/common/expression/TypeCastingExpression.h
  src/common/expression/UnaryExpression.h
Labels: ready-for-testing

#258 refactor keywords
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/RelationalExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#270 add copy assignment operator
  src/common/datatypes/Path.h
  src/common/datatypes/test/PathTest.cpp
Labels: ready-for-testing

#267 Add builtin functions on Edge/Vertex
  cmake/nebula/NebulaCMakeMacros.cmake
  src/common/expression/AttributeExpression.cpp
  src/common/expression/AttributeExpression.h
  src/common/expression/ConstantExpression.h
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-testing

#271 Fixed --gdb-index
  cmake/nebula/NebulaCMakeMacros.cmake
Labels: ready-for-testing

#238 Feature/time creation
  src/common/datatypes/Date.cpp
  src/common/datatypes/Date.h
  src/common/datatypes/test/CMakeLists.txt
  src/common/expression/test/CMakeLists.txt
  src/common/function/FunctionManager.cpp
  src/common/function/TimeFunction.cpp
  src/common/function/TimeFunction.h
  src/common/function/test/CMakeLists.txt
  src/common/function/test/FunctionManagerTest.cpp
  src/common/time/CMakeLists.txt
  src/common/time/TimeUtils.cpp
  src/common/time/TimeUtils.h
  src/common/time/test/CMakeLists.txt
  src/common/time/test/TimeUtilsTest.cpp
Labels: documentation, ready-for-testing

#274 Avoid check failed for index bound check.
  src/common/datatypes/Date.h
Labels: ready-for-testing

#264 Remove the rocksdb's patch
  third-party/patches/rocksdb-5.15.10.patch
Labels: ready-for-testing

#273 Add unknown job command.
  src/common/interface/meta.thrift
Labels: ready-for-testing

#275 Rename &&/|| to AND/OR
  src/common/expression/LogicalExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-testing

#279 support listener for meta
  src/common/base/Status.cpp
  src/common/base/Status.h
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
Labels: ready-for-testing

#282 fixed bug of storage client for index scan
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/clients/storage/GraphStorageClient.h
Labels: ready-for-testing

#280 Remove drain interface from zone
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#286 Support space level statistics
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
  src/common/interface/storage.thrift
Labels: documentation, ready-for-review, ready-for-testing
