Repository vesoft-inc/nebula-common, pull requests merged in 2020-11, with the labels that each got.

#244 Add the timezone information.
  src/common/function/test/FunctionManagerTest.cpp
  src/common/time/CMakeLists.txt
  src/common/time/TimeUtils.cpp
  src/common/time/TimeUtils.h
  src/common/time/TimezoneInfo.cpp
  src/common/time/TimezoneInfo.h
  src/common/time/test/CMakeLists.txt
  src/common/time/test/TimeUtilsTest.cpp
  src/common/time/test/TimezoneInfoTest.cpp
Labels: documentation, ready-for-testing

#281 Add the stateless mark to function.
  src/common/function/FunctionManager.cpp
  src/common/function/FunctionManager.h
Labels: ready-for-testing

#278 Add time schema.
  src/common/meta/NebulaSchemaProvider.cpp
  src/common/meta/NebulaSchemaProvider.h
Labels: ready-for-testing

#269 Support case expression
  src/common/expression/CMakeLists.txt
  src/common/expression/CaseExpression.cpp
  src/common/expression/CaseExpression.h
  src/common/expression/ExprVisitor.h
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/test/EncodeDecodeTest.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-testing

#254 support variable-length string type for index
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#285 Modify listener interface in meta client
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
  src/common/meta/Common.h
Labels: ready-for-review, ready-for-testing

#294 Revert "Modify listener interface in meta client"
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
  src/common/meta/Common.h
Labels: ready-for-testing

#291 Build path expr.
  src/common/expression/CMakeLists.txt
  src/common/expression/ExprVisitor.h
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/PathBuildExpression.cpp
  src/common/expression/PathBuildExpression.h
  src/common/expression/test/EncodeDecodeTest.cpp
  src/common/expression/test/ExpressionContextMock.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#296 Return null/empty if parameters have null/empty.
  src/common/function/FunctionManager.cpp
Labels: ready-for-testing

#299 Flatten LogicalExpression
  src/common/expression/LogicalExpression.cpp
  src/common/expression/LogicalExpression.h
  src/common/expression/test/EncodeDecodeTest.cpp
Labels: ready-for-testing

#292 Support balance id
  src/common/interface/storage.thrift
  src/common/thrift/ThriftTypes.h
Labels: ready-for-review, ready-for-testing

#290 Modify folly::hash::fnv64_buf to MurmurHash2
  src/common/clients/meta/MetaClient.cpp
Labels: ready-for-testing

#300 change tagId/edgeType to tagName/edgeName in StatisItem
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#303 Add .debug_gdb_scripts section to improve debugging experience
  cmake/nebula/ConfigNebulaCommon.cmake
  cmake/nebula/GeneralCMakeOptions.cmake
  src/common/base/CMakeLists.txt
  src/common/base/GdbDebugScript.cpp
Labels: ready-for-testing

#304 Disable --gc-sections if ENABLE_GDB_SCRIPT_SECTION
  cmake/nebula/LinkerConfig.cmake
  src/common/base/GdbDebugScript.cpp
Labels: ready-for-testing

#302 Move ObjectPool into nebula-common
  src/common/base/ObjectPool.h
  src/common/base/test/CMakeLists.txt
  src/common/base/test/ObjectPoolTest.cpp
Labels: ready-for-testing

#301 Add LogicalExpression::setOperands
  src/common/expression/LogicalExpression.h
Labels: ready-for-testing

#276 Fix get local user info thread unsafe
  src/common/clients/meta/MetaClient.cpp
Labels: ready-for-testing

#305 add scalar function
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-testing

#297 Modify listener interface in meta client
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
  src/common/meta/Common.h
Labels: ready-for-review, ready-for-testing

#317 Let datatypes fit c++11 to make client available in c++11.
  src/common/datatypes/DataSet.h
  src/common/datatypes/List.h
Labels: ready-for-testing

#306 Enhance path build expression
  .gitignore
  src/common/datatypes/Path.h
  src/common/expression/PathBuildExpression.cpp
  src/common/expression/test/ExpressionContextMock.cpp
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/FunctionManager.cpp
Labels: ready-for-testing

#260 Support text search.
  src/common/CMakeLists.txt
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/expression/CMakeLists.txt
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/TextSearchExpression.cpp
  src/common/expression/TextSearchExpression.h
  src/common/interface/meta.thrift
  src/common/meta/SchemaManager.h
  src/common/meta/ServerBasedSchemaManager.cpp
  src/common/meta/ServerBasedSchemaManager.h
  src/common/plugin/CMakeLists.txt
  src/common/plugin/fulltext/CMakeLists.txt
  src/common/plugin/fulltext/FTGraphAdapter.h
  src/common/plugin/fulltext/FTStorageAdapter.h
  src/common/plugin/fulltext/FTUtils.h
  src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
  src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.h
  src/common/plugin/fulltext/elasticsearch/ESStorageAdapter.cpp
  src/common/plugin/fulltext/elasticsearch/ESStorageAdapter.h
  src/common/plugin/fulltext/test/CMakeLists.txt
  src/common/plugin/fulltext/test/FulltextPluginTest.cpp
Labels: ready-for-review, ready-for-testing

#314 Add range function
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#316 add columnExpression
  src/common/context/ExpressionContext.h
  src/common/expression/BinaryExpression.cpp
  src/common/expression/CMakeLists.txt
  src/common/expression/ColumnExpression.cpp
  src/common/expression/ColumnExpression.h
  src/common/expression/ConstantExpression.cpp
  src/common/expression/ExprVisitor.h
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/FunctionCallExpression.cpp
  src/common/expression/LabelExpression.cpp
  src/common/expression/PropertyExpression.cpp
  src/common/expression/TypeCastingExpression.cpp
  src/common/expression/UUIDExpression.cpp
  src/common/expression/UnaryExpression.cpp
  src/common/expression/test/ExpressionContextMock.cpp
  src/common/expression/test/ExpressionContextMock.h
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-testing

#320 Modify statis to stat
  src/common/interface/meta.thrift
Labels: ready-for-testing

#308 add string functions
  src/common/datatypes/Date.cpp
  src/common/datatypes/test/ValueTest.cpp
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: documentation, ready-for-review, ready-for-testing

#287 support regular expression
  src/common/base/Base.h
  src/common/context/ExpressionContext.h
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/RelationalExpression.cpp
  src/common/expression/test/ExpressionContextMock.h
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-testing

#318 Add option to disable cxx11 abi.
  CMakeLists.txt
  cmake/nebula/ABIConfig.cmake
  cmake/nebula/ConfigNebulaCommon.cmake
  cmake/nebula/GeneralCMakeOptions.cmake
  cmake/nebula/InstallThirdParty.cmake
  cmake/nebula/ThirdPartyConfig.cmake
Labels: documentation, ready-for-testing

#309 add list functions
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: documentation, ready-for-testing

#256 Let storage client retry when leader changed.
  src/common/clients/storage/GeneralStorageClient.cpp
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/clients/storage/StorageClientBase.cpp
  src/common/clients/storage/StorageClientBase.h
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-testing

#315 Add the data set manipulate method which used in client.
  src/common/datatypes/DataSet.h
  src/common/datatypes/test/CMakeLists.txt
  src/common/datatypes/test/DataSetTest.cpp
Labels: ready-for-testing

#311 fixed meta client cache error
  src/common/clients/meta/MetaClient.cpp
Labels: ready-for-review, ready-for-testing

#321 modify scan interface, unify fetch colname
  src/common/interface/storage.thrift
Labels: ready-for-review, ready-for-testing

#326 Update label attribute expression construction and fix empty value computation
  src/common/datatypes/Value.cpp
  src/common/expression/LabelAttributeExpression.h
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-testing
