Repository vesoft-inc/nebula-common, pull requests merged in 2021-02, with the labels that each got.

#393 storage client no retry， retry is completely invalid.
  src/common/clients/storage/InternalStorageClient.cpp
  src/common/clients/storage/StorageClientBase.h
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-review, ready-for-testing

#399 Enhance subscript expression
  src/common/expression/SubscriptExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-testing

#403 fix edge hash & add edge benchmark
  src/common/datatypes/Edge.cpp
  src/common/datatypes/Edge.h
  src/common/datatypes/test/CMakeLists.txt
  src/common/datatypes/test/EdgeBenchmark.cpp
  src/common/datatypes/test/EdgeTest.cpp
Labels: ready-for-testing

#396 fix agg and List operator
  src/common/datatypes/Value.cpp
  src/common/datatypes/test/ValueTest.cpp
  src/common/expression/AggregateExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#377 Add flag to determine whether partial success results are valid
  src/common/base/Status.cpp
  src/common/base/Status.h
  src/common/meta/NebulaSchemaProvider.h
Labels: ready-for-review, ready-for-testing

#408 fix null toString
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#392 Enhanced StatsManager utility
  src/common/stats/CMakeLists.txt
  src/common/stats/Stats.cpp
  src/common/stats/Stats.h
  src/common/stats/StatsManager.cpp
  src/common/stats/StatsManager.h
  src/common/stats/test/StatsManagerBenchmark.cpp
  src/common/stats/test/StatsManagerCrossLevelTest.cpp
  src/common/stats/test/StatsManagerRateTest.cpp
  src/common/stats/test/StatsManagerTest.cpp
  src/common/webservice/test/StatsReaderTest.cpp
Labels: ready-for-testing

#410 add function sign
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: documentation, ready-for-testing

#414 reveal the hidden leader changed error code
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-review, ready-for-testing

#417 Add error code for index write
  src/common/interface/storage.thrift
Labels: ready-for-review, ready-for-testing

#406 Handle the responses via different evb.
  src/common/clients/storage/StorageClientBase.h
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-testing

#420 Fix StorageRpcResponse dead lock.
  src/common/clients/storage/StorageClientBase.h
Labels: ready-for-testing
