Repository vesoft-inc/nebula-common, pull requests merged in 2021-03, with the labels that each got.

#416 Add mathematical functions
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#424 always send storage leaders to meta
  src/common/clients/meta/MetaClient.cpp
Labels: ready-for-review, ready-for-testing

#422 Add bound check to int() and update tests for type casting
  src/common/datatypes/Value.cpp
  src/common/datatypes/test/ValueTest.cpp
Labels: ready-for-review, ready-for-testing

#426 empty to INT OR FLOAT
  src/common/expression/TypeCastingExpression.cpp
Labels: ready-for-review, ready-for-testing

#412 Fix TypeCastExpression
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/datatypes/test/ValueTest.cpp
  src/common/expression/TypeCastingExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: need-to-discuss, ready-for-review, ready-for-testing

#415 Fix the value of sha in http server.
  cmake/nebula/ConfigNebulaCommon.cmake
  src/common/CMakeLists.txt
  src/common/http/test/CMakeLists.txt
  src/common/version/CMakeLists.txt
  src/common/version/Version.cpp.in
  src/common/version/Version.h
  src/common/webservice/StatusHandler.cpp
  src/common/webservice/test/CMakeLists.txt
  src/common/webservice/test/StatusHandlerTest.cpp
Labels: bug, ready-for-review, ready-for-testing

#413 Make flags/stats/status HTTP API confirm to RESTful specification
  src/common/http/HttpClient.cpp
  src/common/http/HttpClient.h
  src/common/stats/StatsManager.cpp
  src/common/webservice/GetFlagsHandler.cpp
  src/common/webservice/GetFlagsHandler.h
  src/common/webservice/GetStatsHandler.cpp
  src/common/webservice/GetStatsHandler.h
  src/common/webservice/SetFlagsHandler.cpp
  src/common/webservice/SetFlagsHandler.h
  src/common/webservice/WebService.cpp
  src/common/webservice/test/FlagsAccessTest.cpp
  src/common/webservice/test/StatsReaderTest.cpp
  src/common/webservice/test/TestUtils.h
Labels: documentation, ready-for-review, ready-for-testing

#429 fix typeCasting function
  src/common/datatypes/Value.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#401 fix RelationalExpression
  src/common/datatypes/Path.h
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/datatypes/test/ValueTest.cpp
  src/common/expression/RelationalExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#430 Fix value operator
  src/common/datatypes/Value.cpp
  src/common/datatypes/test/ValueTest.cpp
Labels: ready-for-review, ready-for-testing

#409 Add isNull/isNotNull operator
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/UnaryExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: documentation, ready-for-review, ready-for-testing

#419 Add expired time factor.
  src/common/clients/meta/MetaClient.cpp
Labels: ready-for-testing

#434 small fix for upgrade
  src/common/expression/Expression.h
Labels: ready-for-review, ready-for-testing

#432 add exists function
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#425 Simplify the logical to invalid leader.
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-review, ready-for-testing

#298 Support download and ingest in job manager
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#431 reconnect when EOF
  src/common/thrift/CMakeLists.txt
  src/common/thrift/ReconnectingRequestChannel.cpp
  src/common/thrift/ThriftClientManager.inl
Labels: ready-for-review, ready-for-testing

#444 fix toString of IS_NULL
  src/common/expression/UnaryExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#450 fixed unstable test plugin_fulltext_test
  src/common/plugin/fulltext/test/FulltextPluginTest.cpp
Labels: ready-for-review, ready-for-testing

#452 fix nullptr ThriftClient
  src/common/thrift/ThriftClientManager.inl
Labels: ready-for-review, ready-for-testing

#449 delete spinLock of FunctionManager
  src/common/function/FunctionManager.cpp
  src/common/function/FunctionManager.h
Labels: ready-for-review, ready-for-testing

#439 Get parts num out of part id.
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-testing

#451 fix in operator
  src/common/expression/RelationalExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#443 add exist expression
  src/common/datatypes/Edge.cpp
  src/common/datatypes/Edge.h
  src/common/datatypes/Vertex.cpp
  src/common/datatypes/Vertex.h
  src/common/expression/ListComprehensionExpression.cpp
  src/common/expression/ListComprehensionExpression.h
  src/common/expression/PredicateExpression.cpp
  src/common/expression/PredicateExpression.h
  src/common/expression/ReduceExpression.cpp
  src/common/expression/ReduceExpression.h
Labels: ready-for-review, ready-for-testing

#457 update gflags to register by default
  src/common/meta/GflagsManager.cpp
Labels: ready-for-review, ready-for-testing

#453 add rand function
  src/common/function/FunctionManager.cpp
Labels: ready-for-review, ready-for-testing

#454 compatible with opencypher
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#437 add AggFunctionManager
  src/common/datatypes/test/CMakeLists.txt
  src/common/expression/AggregateExpression.cpp
  src/common/expression/AggregateExpression.h
  src/common/expression/test/CMakeLists.txt
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/AggFunctionManager.cpp
  src/common/function/AggFunctionManager.h
  src/common/function/CMakeLists.txt
  src/common/function/FunctionManager.cpp
  src/common/function/FunctionManager.h
  src/common/function/test/AggFunctionManagerTest.cpp
  src/common/function/test/CMakeLists.txt
Labels: not-ready-to-review, ready-for-testing

#438 select leader in round-robin
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/clients/storage/StorageClientBase.h
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-review, ready-for-testing

#463 Add partial succeeded.
  src/common/graph/Response.h
  src/common/interface/graph.thrift
Labels: ready-for-testing

#456 Fix some compiler warning.
  src/common/base/EitherOr.h
  src/common/base/StatusOr.h
  src/common/base/test/RangeVsTransformBenchmark.cpp
  src/common/datatypes/Value.cpp
  src/common/fs/FileUtils.h
  src/common/stats/StatsManager.h
Labels: ready-for-review, ready-for-testing

#460 add bit functions
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#427 Support negative correlativity
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#470 Add getStorageHosts from cache
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
Labels: ready-for-testing

#469 fix missing type in getFlags
  src/common/webservice/GetFlagsHandler.cpp
  src/common/webservice/test/FlagsAccessTest.cpp
Labels: ready-for-review, ready-for-testing

#468 Improve clusterIdsToHosts.
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/clients/storage/InternalStorageClient.cpp
  src/common/clients/storage/StorageClientBase.h
  src/common/clients/storage/StorageClientBase.inl
Labels: hold on, ready-for-testing

#471 Fix typo
  src/common/interface/storage.thrift
Labels: ready-for-review, ready-for-testing

#474 fixed unstable testcase
  src/common/plugin/fulltext/test/FulltextPluginTest.cpp
Labels: ready-for-review, ready-for-testing

#476 Lower ThriftClientManager log level
  src/common/base/SlowOpTracker.h
  src/common/thrift/ThriftClientManager.inl
Labels: ready-for-review, ready-for-testing

#448 Push down some expressions to the storage layer
  src/common/expression/Expression.cpp
  src/common/expression/VariableExpression.cpp
  src/common/expression/VariableExpression.h
Labels: ready-for-testing

#445 add isEmpty
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/UnaryExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#407 Cache the function when function call evaluation to avoid duplicate l…
  src/common/expression/FunctionCallExpression.cpp
  src/common/expression/FunctionCallExpression.h
  src/common/expression/test/CMakeLists.txt
  src/common/expression/test/ExpressionTest.cpp
  src/common/expression/test/FunctionCallExpressionBenchmark.cpp
Labels: hold on, ready-for-testing

#477 fix agg
  src/common/expression/AggregateExpression.h
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/AggFunctionManager.cpp
  src/common/function/test/AggFunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#472 Disable the pointer-bool conversion for value.
  src/common/datatypes/Value.h
  src/common/datatypes/test/ValueTest.cpp
Labels: ready-for-review, ready-for-testing

#478 Revert "fix agg"
  src/common/expression/AggregateExpression.h
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/AggFunctionManager.cpp
  src/common/function/test/AggFunctionManagerTest.cpp
Labels: ready-for-testing
