Repository vesoft-inc/nebula-common, pull requests merged in 2021-04, with the labels that each got.

#467 Add agg cache
  src/common/expression/AggregateExpression.cpp
  src/common/expression/AggregateExpression.h
  src/common/expression/test/AggregateExpressionBenchmark.cpp
  src/common/expression/test/CMakeLists.txt
Labels: ready-for-review, ready-for-testing

#390 Fix path duplicate functions and add value hash/equal benchmark
  src/common/datatypes/Path.cpp
  src/common/datatypes/test/CMakeLists.txt
  src/common/datatypes/test/PathTest.cpp
  src/common/datatypes/test/ValueBenchmark.cpp
Labels: ready-for-testing

#481 Add interfaces to expression
  src/common/expression/Expression.h
  src/common/expression/LogicalExpression.h
  src/common/expression/RelationalExpression.h
Labels: ready-for-review, ready-for-testing

#483 fixed fulltext security error
  src/common/plugin/fulltext/FTUtils.h
Labels: ready-for-review, ready-for-testing

#480 fix agg
  src/common/expression/AggregateExpression.cpp
  src/common/expression/AggregateExpression.h
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/AggFunctionManager.cpp
  src/common/function/test/AggFunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#486 Cherrypick #390 #483 #477 #478 #480
  src/common/datatypes/Path.cpp
  src/common/datatypes/test/CMakeLists.txt
  src/common/datatypes/test/PathTest.cpp
  src/common/datatypes/test/ValueBenchmark.cpp
  src/common/expression/AggregateExpression.h
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/AggFunctionManager.cpp
  src/common/function/test/AggFunctionManagerTest.cpp
  src/common/plugin/fulltext/FTUtils.h
Labels: ready-for-testing

#418 Fix nonegative comparison.
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#489 [Simple] Add isArithmeticExpr() to expression
  src/common/expression/ArithmeticExpression.h
  src/common/expression/Expression.h
Labels: ready-for-review, ready-for-testing

#491 fix substr crash
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#482 Support aarch64
  src/common/time/Duration.cpp
  src/common/time/Duration.h
  src/common/time/WallClock.cpp
  src/common/time/detail/TscHelper.cpp
  src/common/time/detail/TscHelper.h
  third-party/install-gcc.sh
  third-party/install-third-party.sh
Labels: ready-for-testing

#493 Cherrypick #491
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-testing

#495 ##SIMPLE## Added thrift codegen for Rust
  cmake/ThriftGenerate.cmake
Labels: ready-for-testing

#475 Feature/comment field
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#485 Send leader term in heart beat
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#499 Revert "Send leader term in heart beat"
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#500 get lastest version edge schema
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
Labels: ready-for-review, ready-for-testing

#498 fix ceil round floor
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#487 fix case sensitivity of function name
  src/common/function/FunctionManager.cpp
  src/common/function/FunctionManager.h
Labels: Harmful to CI, ready-for-review, ready-for-testing

#473 insert vertex if not exists
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/clients/storage/GraphStorageClient.h
  src/common/interface/storage.thrift
Labels: Harmful to CI, ready-for-review, ready-for-testing

#494 add invalid job errorcode
  src/common/clients/meta/MetaClient.cpp
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#502 Revert "Revert "Send leader term in heart beat""
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#501 add alllatestVerEdgeSchema interface
  src/common/meta/SchemaManager.h
  src/common/meta/ServerBasedSchemaManager.cpp
  src/common/meta/ServerBasedSchemaManager.h
Labels: hold on, ready-for-review, ready-for-testing

#503 Feature/gen rust
  cmake/ThriftGenerate.cmake
  src/common/interface/CMakeLists.txt
Labels: ready-for-testing

#505 Ignore the mv issue first.
  cmake/ThriftGenerate.cmake
Labels: ready-for-testing

#510 fix in op
  src/common/expression/RelationalExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#511 Fix regex
  src/common/expression/RelationalExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#512 fix some relational expressions with Null/badNull
  src/common/expression/RelationalExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: ready-for-review, ready-for-testing

#515 [OpenCypher Compatibility] Support timestamp() with empty parameter
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-review, ready-for-testing

#509 [opencypher compatibility] Support using exists with dynamic map
  src/common/expression/PredicateExpression.cpp
Labels: ready-for-review, ready-for-testing

#519 add non-const getter for LabelAttrExpr
  src/common/expression/LabelAttributeExpression.h
Labels: ready-for-review, ready-for-testing

#522 add errorcode for update
  src/common/interface/storage.thrift
Labels: ready-for-review, ready-for-testing

#514 Fix the rust file was covered
  cmake/ThriftGenerate.cmake
Labels: ready-for-testing

#507 Raft interface should not export to another client
  src/common/interface/raftex.thrift
Labels: ready-for-review, ready-for-testing

#368 Modify the createcheckpoint interface of storage
  src/common/interface/storage.thrift
Labels: ready-for-testing
