Repository vesoft-inc/nebula-common, pull requests merged in 2021-01, with the labels that each got.

#375 Fix propName
  src/common/clients/storage/GraphStorageClient.cpp
Labels: ready-for-testing

#376 Fix some move issue in storage client.
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/clients/storage/StorageClientBase.inl
Labels: ready-for-testing

#382 Fix the toString format of map expression.
  src/common/expression/ContainerExpression.cpp
  src/common/expression/test/ExpressionTest.cpp
Labels: bug, ready-for-testing

#354 AggregateExpression Implementation
  .gitignore
  src/common/expression/AggregateExpression.cpp
  src/common/expression/AggregateExpression.h
  src/common/expression/CMakeLists.txt
  src/common/expression/ConstantExpression.h
  src/common/expression/ExprVisitor.h
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/test/EncodeDecodeTest.cpp
  src/common/expression/test/ExpressionTest.cpp
  src/common/function/AggregateFunction.cpp
  src/common/function/AggregateFunction.h
  src/common/function/CMakeLists.txt
  src/common/function/test/AggregateFunctionTest.cpp
  src/common/function/test/CMakeLists.txt
Labels: documentation, ready-for-review, ready-for-testing

#383 Task report itself finish to job manager
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#384 Support download and ingest
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
Labels: ready-for-review, ready-for-testing

#345 Support predicate expressions
  src/common/expression/CMakeLists.txt
  src/common/expression/ExprVisitor.h
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/PredicateExpression.cpp
  src/common/expression/PredicateExpression.h
  src/common/expression/test/EncodeDecodeTest.cpp
  src/common/expression/test/ExpressionContextMock.h
  src/common/expression/test/ExpressionTest.cpp
Labels: documentation, hold on, ready-for-review, ready-for-testing

#385 cherry patch from nebula 1.0
  src/common/clients/meta/MetaClient.cpp
Labels: ready-for-review, ready-for-testing

#386 add one error code
  src/common/interface/meta.thrift
Labels: ready-for-review, ready-for-testing

#379 Add getAllLatestVerTagSchema()
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/meta/SchemaManager.h
  src/common/meta/ServerBasedSchemaManager.cpp
  src/common/meta/ServerBasedSchemaManager.h
Labels: ready-for-review, ready-for-testing

#391 Add the missing error code in metaclient
  src/common/clients/meta/MetaClient.cpp
Labels: ready-for-testing

#380 support gets the value at specified row, col of a dataset
  src/common/function/FunctionManager.cpp
Labels: ready-for-testing

#394 Fix set and unify limit
  src/common/clients/storage/GraphStorageClient.cpp
  src/common/interface/storage.thrift
Labels: ready-for-review, ready-for-testing

#346 Support reduce expression
  src/common/expression/CMakeLists.txt
  src/common/expression/ExprVisitor.h
  src/common/expression/Expression.cpp
  src/common/expression/Expression.h
  src/common/expression/ListComprehensionExpression.cpp
  src/common/expression/PredicateExpression.cpp
  src/common/expression/ReduceExpression.cpp
  src/common/expression/ReduceExpression.h
  src/common/expression/test/EncodeDecodeTest.cpp
  src/common/expression/test/ExpressionContextMock.h
  src/common/expression/test/ExpressionTest.cpp
Labels: documentation, ready-for-review, ready-for-testing

#397 change ver of edge key from i64 to char
  src/common/thrift/ThriftTypes.h
Labels: ready-for-review, ready-for-testing

#402 fix properties(MAP)
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-testing
