Repository vesoft-inc/nebula-common, pull requests merged in 2021-07, with the labels that each got.

#570 Update stats format when read all values
  src/common/stats/StatsManager.cpp
  src/common/stats/test/StatsManagerTest.cpp
Labels: ready-for-testing

#565 Slow query.
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/graph/Response.h
  src/common/interface/common.thrift
  src/common/interface/meta.thrift
  src/common/session/SessionManager.h
  src/common/thrift/ThriftTypes.h
Labels: ready-for-testing

#492 Cache partition term
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/interface/meta.thrift
Labels: ready-for-testing

#562 rebuild fulltext indexes via listener
  src/common/interface/meta.thrift
Labels: ready-for-testing

#523 Get current time with milliseconds precision.
  src/common/function/FunctionManager.cpp
  src/common/time/TimeUtils.h
Labels: bug, doc affected, ready-for-testing

#579 Fix operator+ for string and float
  src/common/datatypes/Value.cpp
  src/common/datatypes/test/ValueTest.cpp
Labels: ready-for-testing

#584 Fix casting a string to a string.
  src/common/expression/TypeCastingExpression.cpp
  src/common/expression/test/TypeCastingExpressionTest.cpp
Labels: ready-for-testing

#582 Fix the exists eval for null properties.
  src/common/datatypes/Edge.cpp
  src/common/datatypes/Edge.h
  src/common/datatypes/Vertex.cpp
  src/common/datatypes/Vertex.h
  src/common/expression/PredicateExpression.cpp
Labels: bug, ready-for-testing

#580 small fix for libc selection version
  third-party/install-third-party.sh
Labels: ready-for-testing

#591 Modify the return value of partId function
  src/common/clients/meta/MetaClient.cpp
  src/common/clients/meta/MetaClient.h
  src/common/clients/storage/InternalStorageClient.cpp
Labels: ready-for-testing

#590 Add isContainerExpr() interface
  src/common/expression/ContainerExpression.h
  src/common/expression/Expression.h
Labels: ready-for-testing

#588 Adapte to kylin and mips64el
  cmake/CPackage.cmake
  cmake/nebula/LinkerConfig.cmake
  src/common/base/ObjectPool.h
  src/common/time/WallClock.cpp
Labels: ready-for-testing

#589 Add more datetime literal format.
  src/common/time/TimeUtils.h
  src/common/time/test/TimeUtilsTest.cpp
Labels: ready-for-testing

#593 fix and simplify SubscriptRangeExpression's eval()
  src/common/expression/SubscriptExpression.cpp
  src/common/expression/test/SubscriptExpressionTest.cpp
Labels: ready-for-testing

#595 Fix toInteger()
  src/common/datatypes/Value.cpp
  src/common/datatypes/test/ValueTest.cpp
Labels: ready-for-testing

#578 link zlib to fix arm compilation
  cmake/nebula/NebulaCMakeMacros.cmake
Labels: ready-for-testing

#586 Support to get attribute of date/time/datetime.
  src/common/datatypes/Map.h
  src/common/expression/AttributeExpression.cpp
  src/common/expression/test/AggregateExpressionTest.cpp
  src/common/expression/test/AttributeExpressionTest.cpp
  src/common/expression/test/SubscriptExpressionTest.cpp
  src/common/function/AggFunctionManager.cpp
  src/common/time/TimeUtils.h
Labels: ready-for-testing
